<?php

declare(strict_types=1);

namespace AITracer\Tests;

use AITracer\AITracer;
use AITracer\Config;
use AITracer\Trace;
use AITracer\Exceptions\AITracerException;
use PHPUnit\Framework\TestCase;
use InvalidArgumentException;

class AITracerTest extends TestCase
{
    protected function tearDown(): void
    {
        // Clear singleton instance
        $reflection = new \ReflectionClass(AITracer::class);
        $property = $reflection->getProperty('instance');
        $property->setAccessible(true);
        $property->setValue(null, null);
    }

    public function testConstructorWithValidOptions(): void
    {
        $tracer = new AITracer([
            'api_key' => 'at-test-key-123',
            'project' => 'test-project',
            'enabled' => false, // Disable actual API calls
        ]);

        $this->assertInstanceOf(AITracer::class, $tracer);
        $this->assertTrue($tracer->getConfig()->enabled === false);
    }

    public function testConstructorThrowsOnMissingApiKey(): void
    {
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage('API key is required');

        new AITracer([
            'project' => 'test-project',
        ]);
    }

    public function testConstructorThrowsOnInvalidApiKeyFormat(): void
    {
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage('Invalid API key format');

        new AITracer([
            'api_key' => 'invalid-key',
            'project' => 'test-project',
        ]);
    }

    public function testConstructorThrowsOnMissingProject(): void
    {
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage('Project is required');

        new AITracer([
            'api_key' => 'at-test-key',
        ]);
    }

    public function testSingletonInstance(): void
    {
        $tracer = new AITracer([
            'api_key' => 'at-test-key',
            'project' => 'test-project',
            'enabled' => false,
        ]);

        $this->assertSame($tracer, AITracer::getInstance());
    }

    public function testTraceCreation(): void
    {
        $tracer = new AITracer([
            'api_key' => 'at-test-key',
            'project' => 'test-project',
            'enabled' => false,
        ]);

        $trace = $tracer->trace('custom-trace-id', 'Test Trace');

        $this->assertInstanceOf(Trace::class, $trace);
        $this->assertEquals('custom-trace-id', $trace->getId());
        $this->assertEquals('Test Trace', $trace->getName());
    }

    public function testTraceAutoGeneratedId(): void
    {
        $tracer = new AITracer([
            'api_key' => 'at-test-key',
            'project' => 'test-project',
            'enabled' => false,
        ]);

        $trace = $tracer->trace();

        $this->assertNotEmpty($trace->getId());
        $this->assertEquals(32, strlen($trace->getId())); // 16 bytes = 32 hex chars
    }

    public function testEnableDisable(): void
    {
        $tracer = new AITracer([
            'api_key' => 'at-test-key',
            'project' => 'test-project',
            'enabled' => true,
        ]);

        $this->assertTrue($tracer->isEnabled());

        $tracer->disable();
        $this->assertFalse($tracer->isEnabled());

        $tracer->enable();
        $this->assertTrue($tracer->isEnabled());
    }
}
